name = "backend"
main = "src/index.ts"
compatibility_date = "2024-10-31"

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [vars]
# DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNTRiYjAzMTctMTc5Zi00ZWJiLWJiMTMtNTY1M2M1OTBmOTM1IiwidGVuYW50X2lkIjoiOTAwMWQ5MmY2ZjgxZjY0NzA1OGViOWU3ODgwZDBkN2NmOTZlYTM4NDNjYzIwNjQ1ODk0NjhmMzAwZjE5Y2NhOSIsImludGVybmFsX3NlY3JldCI6IjlkNjhlZTMyLTc3NTUtNGQ4Ny05YjViLWFlYzlhYTkzYmIzZSJ9.-BSnHjm6XsWS7MYhKQH2CRXVs9OumqFld1TcPmphVrI"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1